---
title: Public perceptions of multiple risks during the COVID-19 pandemic in Italy
  and Sweden. Reproducing original findings and extending it with data for Poland.
author: "Mateusz Baryła, Konrad Lewszyk"
date: "May 26, 2022"
output:
  slidy_presentation: default
  beamer_presentation: default
---

```{r, echo = FALSE, results = 'hide', message = FALSE, warning = FALSE, fig.show = 'hide'}
library(dplyr)
library(DiagrammeR)
```
# Agenda

1. Searching for the right study
2. The original research
3. Survey replication
4. Transforming the data
5. Coding
6. Results

# Searching for the study

# Original Study

# Extended study

# Original data

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.show = 'hide'}
df <- read.csv("data/Dataset_round1_august2020.csv", header = TRUE, na = "999")
df %>% head()
```

# Gathered data

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.show = 'hide'}
df_new <- read.csv("data/survey.csv", header = TRUE, na = "999")
df_new %>% head()
```

# Steps to preprocess
<center>
```{r echo = FALSE,  message = FALSE, warning = FALSE, fig.show = 'hide', fig.align='center'}
grViz("digraph {
graph [layout = dot, rankdir = TB]

node [shape = rectangle]
rec1 [label = 'Step 1. Creating mapping tibble between original column names and collected ones']
rec2 [label = 'Step 2. Splitting the data depending on scale (Likert, dichotomous, numeric']
rec3 [label =  'Step 3. For each datarame we do a conversion between original values mainly with pivoting.']
rec4 [label = 'Step 4. Joining the DataFrames into one, final one.']

# edge definitions with the node IDs
rec1 -> rec2 -> rec3 -> rec4
}",
                  height = 300)
```
</center>

# Full reproducibility
groundhog library
GitHub
Google Drive

# Results

